config/routes.rb
Rails.application.routes.draw do

  resources :schools
  resources :teachers
  resources :students
  resources :courses

  get     '/teachers/:id/student', to: 'teachers#show'

  root   'schools#index'

end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :teacher
end

app/models/school.rb
class School < ActiveRecord::Base
  has_many :teachers
  has_many :students, through: :teachers
  has_many :courses, through: :teachers
end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :teacher
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  belongs_to :school, :dependent => :destroy
  has_many :students
  has_many :courses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  def index
    page  = (params[:page]  ||  0).to_i
    courses = Course.limit(25).offset(page * 25)
    render locals: { courses: courses, page: page }
  end

  def show
  end

end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController

  def index
    page  = (params[:page]  ||  0).to_i
    schools = School.limit(25).offset(page * 25)
    render locals: { schools: schools, page: page }
  end

  def show
    school = School.find(params[:id])
    render locals: { school: school }
  end


end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
  end

  def show
  end



end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController

  def index
    page  = (params[:page]  ||  0).to_i
    teachers = Teacher.limit(25).offset(page * 25)
    render locals: { teachers: teachers, page: page }
  end

  def show
    teacher = Teacher.find(params[:id])
    render locals: { teacher: teacher }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/courses/index.html.erb
<h1>Courses</h1>

<ul class="list-group">
  <% courses.each do |course| %>
  <li class="list-group-item"><%= course.id %>.) <%= link_to(course.name, courses_path(courses)) %></li>
 <% end %>

<nav>
  <ul class="pager">
    <li><%= link_to('Teachers index', teachers_path) %></li>
    <li><%= link_to('Schools index', schools_path) %></li>
  </ul>
</nav>


  <%= link_to("< Previous page" , courses_path(page: page - 1)) unless page < 0 %>
  <%= link_to("More on next page >", courses_path(page: page + 1)) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Schoolapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<header class>
  <ul class="nav nav-tabs">
    <li role="presentation" class="active"><a href="#">Home</a></li>
    <li role="presentation"><a href="#">Courses</a></li>
    <li role="presentation"><a href="#">Teachers</a></li>
  </ul>
</header>
<body class="text-center">

<%= yield %>
</body>

<nav>
  <ul class="pager">
    <li><%= link_to('Home', root_path) %></li>
  </ul>
</nav>

<footer class=>
created by @mmdotz
</footer>
</html>

app/views/schools/create.html.erb
<h1>Schools#create</h1>
<p>Find me in app/views/schools/create.html.erb</p>

app/views/schools/destroy.html.erb
<h1>Schools#destroy</h1>
<p>Find me in app/views/schools/destroy.html.erb</p>

app/views/schools/index.html.erb
<h1>Schools</h1>


  <ul class="list-group">
    <% schools.each do |school| %>
      <li class="list-group-item"><%= link_to( school.name, school_path(school)) %> </li>
    <% end %>
  </ul>

  <nav>
    <ul class="pager">
      <li><%= link_to('Teachers index', teachers_path) %></li>
      <li><%= link_to('Courses index', courses_path) %></li>
    </ul>
  </nav>

  <footer>
  <!-- offset -->
  <%= link_to("< Previous page" , root_path(page: page - 1)) unless page < 0 %>
  <%= link_to("More on next page >", root_path(page: page + 1)) if schools.size >= 25 %>
  </footer>

app/views/schools/new.html.erb
<h1>Schools#new</h1>
<p>Find me in app/views/schools/new.html.erb</p>

app/views/schools/show.html.erb
<h2><%= school.name %></h2>

<h3> School stats :</h3>

<table class="table table-hover">
  <thead>
    <th> Student ID </th>
    <th> Student </th>
    <th> Course teacher </th>
    <th> School course </th>
  </thead>
      <% school.students.each do |student| %>
  <tbody>
    <tr>
      <td><%= student.id %></td>
      <td><%= student.name %></td>
      <td><%= student.teacher.name %></td>
      <td><%= school.courses.name %></td>
    </tr>
    </tbody>
  <% end %>
</table>

<table class="table table-hover">
  <thead>
    <th> Teacher</th>
    <th> Course </th>
  </thead>
    <% school.teachers.each do |teacher| %>
  <tbody>
    <tr>
      <td><%= teacher.name %></td>
      <td><%= teacher.courses.name %></td>
    </tr>
  </tbody>
  <% end %>
</table>

<table class="table table-hover">
  <thead>
    <th> Course name </th>
  </thead>
    <% school.courses.each do |course| %>
  <tbody>
    <tr>
      <%= course.name %>
    </tr>
  <tbody>
  <% end %>
</table>

  <p>Number of students: <%= school.students.count %></p>
  <p>Number of teachers: <%= school.teachers.count %></p>
  <p>Number of courses: <%= school.courses.count %></p>

app/views/schools/update.html.erb
<h1>Schools#update</h1>
<p>Find me in app/views/schools/update.html.erb</p>

app/views/teachers/index.html.erb
<h2>Teachers</h2>


<ul class="list-group">
  <% teachers.each do |teacher| %>
  <li class="list-group-item"><%= link_to(teacher.name, teacher_path(teacher)) %></li>
 <% end %>
</ul>



<nav>
  <ul class="pager">
    <li><%= link_to('School index', schools_path) %></li>
    <li><%= link_to('Courses index', courses_path) %></li>
  </ul>
</nav>


<%= link_to("< Previous page" , teachers_path(page: page - 1)) unless page < 0 %>
<%= link_to('More on next page >', teachers_path(page: page + 1)) if teachers.size >= 25  %>

app/views/teachers/show.html.erb
<h2>Stats for <%= teacher.name %></h2>

<p> Students :
<%teacher.students.each do |student| %>
  <%= student.name %>
  <br>
 <% end %><br>
   Number of students: <%= teacher.students.count %>
  </p>

  <p> Courses :
<% teacher.courses.each do |course| %>
  <%= course.name %><br>
  <% end %>
   Number of courses: <%= teacher.courses.count %>

  </p>